version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2021-11-03T03-36-36Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=localhost
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: {}
